spring:
  datasource:
    password:
    url: jdbc:mysql://localhost/serverdb?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto:create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      show-sql: true